[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd diindiin && npm install"
]

[phases.build]
cmds = [
  "cd diindiin && npm run build"
]

[start]
cmd = "cd diindiin && node dist/index.js"

